apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: cafe-ingress
  # use annotations with k8s version < 1.18.0
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  # ingressClassName: nginx # use only with k8s version >= 1.18.0
  rules:
  - host: cafe.example.com
    http:
      paths:
      - path: /tea
        backend:
          serviceName: tea-svc
          servicePort: 80
      - path: /coffee
        backend:
          serviceName: coffee-svc
          servicePort: 80